# Generated by Django 3.1.7 on 2021-03-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
